version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000" # Puerto para agentes (opcional)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Para usar Docker desde Jenkins (builds dentro del contenedor)
    restart: unless-stopped
    user: root # necesario para acceder al docker.sock

volumes:
  jenkins_home:
